[tool.poetry]
name = "aio-kong"
version = "0.9.0"
description = "Asynchronous Kong Client"
authors = ["Luca <luca@quantmind.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.8.1"
click = "^8.0.3"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
black = "^21.11b1"
isort = "^5.10.1"
mypy = "^0.910"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-aiohttp = "^0.3.0"
flake8 = "^4.0.1"
flake8-blind-except = "^0.2.0"
flake8-commas = "^2.1.0"
codecov = "^2.1.12"
coverage = "^6.2"
python-dotenv = "^0.19.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
