name: build

on:
  push:
    branches-ignore:
      - deploy
    tags-ignore:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_ENV: ci
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: run services
        run: make services-ci
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install
      - name: check version
        run: make test-version
      - name: run linters
        run: make lint-check
      - name: run tests
        run: make test
      - name: upload coverage
        if: matrix.python-version == '3.11'
        run: make test-codecov
      - name: publish
        if: ${{ matrix.python-version == '3.11' && github.event.head_commit.message == 'release' }}
        run: make publish
